package ru.tomtrix.fvds.db;
// Generated Jun 20, 2014 5:23:06 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames={"user_id", "name"}) 
)
public class Category  implements java.io.Serializable {


     private Long categoryId;
     private Category category;
     private Usr usr;
     private String name;
     private Set<Category> categories = new HashSet<Category>(0);
     private Set<Item> items = new HashSet<Item>(0);

    public Category() {
    }

	
    public Category(Usr usr, String name) {
        this.usr = usr;
        this.name = name;
    }
    public Category(Category category, Usr usr, String name, Set<Category> categories, Set<Item> items) {
       this.category = category;
       this.usr = usr;
       this.name = name;
       this.categories = categories;
       this.items = items;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="category_id", unique=true, nullable=false)
    public Long getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="parent_id")
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Usr getUsr() {
        return this.usr;
    }
    
    public void setUsr(Usr usr) {
        this.usr = usr;
    }
    
    @Column(name="name", nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="category")
    public Set<Category> getCategories() {
        return this.categories;
    }
    
    public void setCategories(Set<Category> categories) {
        this.categories = categories;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="category")
    public Set<Item> getItems() {
        return this.items;
    }
    
    public void setItems(Set<Item> items) {
        this.items = items;
    }




}


