package ru.tomtrix.fvds.db;
// Generated 31-Dec-2022 18:01:11 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name="item"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames={"category_id", "name"}) 
)
public class Item  implements java.io.Serializable {


     private Long itemId;
     private Category category;
     private String name;
     private Set<Operation> operations = new HashSet<Operation>(0);

    public Item() {
    }

	
    public Item(Category category, String name) {
        this.category = category;
        this.name = name;
    }
    public Item(Category category, String name, Set<Operation> operations) {
       this.category = category;
       this.name = name;
       this.operations = operations;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="item_id", unique=true, nullable=false)
    public Long getItemId() {
        return this.itemId;
    }
    
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="category_id", nullable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    
    @Column(name="name", nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="item")
    public Set<Operation> getOperations() {
        return this.operations;
    }
    
    public void setOperations(Set<Operation> operations) {
        this.operations = operations;
    }




}


