package ru.tomtrix.fvds.db;
// Generated Jun 20, 2014 5:23:06 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name="person"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames={"user_id", "name"}) 
)
public class Person  implements java.io.Serializable {


     private Long personId;
     private Usr usr;
     private String name;
     private Set<Operation> operations = new HashSet<Operation>(0);

    public Person() {
    }

	
    public Person(Usr usr, String name) {
        this.usr = usr;
        this.name = name;
    }
    public Person(Usr usr, String name, Set<Operation> operations) {
       this.usr = usr;
       this.name = name;
       this.operations = operations;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="person_id", unique=true, nullable=false)
    public Long getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(Long personId) {
        this.personId = personId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Usr getUsr() {
        return this.usr;
    }
    
    public void setUsr(Usr usr) {
        this.usr = usr;
    }
    
    @Column(name="name", nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="person")
    public Set<Operation> getOperations() {
        return this.operations;
    }
    
    public void setOperations(Set<Operation> operations) {
        this.operations = operations;
    }




}


